import os

DEBUG = False
SECRET_KEY = 'topsecret'
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SQLALCHEMY_TRACK_MODIFICATIONS = False
ACCOUNT_ACTIVATION = True
ROOT_URL = 'localhost'
REDIRECT_HTTP = True
